//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.CORC
{
    [Serializable]
    public class JointScaled32Msg : Message
    {
        public const string k_RosMessageName = "CORC/JointScaled32";
        public override string RosMessageName => k_RosMessageName;

        public float tau_s;
        public float q;
        public float tau_df;
        public float tau_pf;
        public float q_df;
        public float q_pf;

        public JointScaled32Msg()
        {
            this.tau_s = 0.0f;
            this.q = 0.0f;
            this.tau_df = 0.0f;
            this.tau_pf = 0.0f;
            this.q_df = 0.0f;
            this.q_pf = 0.0f;
        }

        public JointScaled32Msg(float tau_s, float q, float tau_df, float tau_pf, float q_df, float q_pf)
        {
            this.tau_s = tau_s;
            this.q = q;
            this.tau_df = tau_df;
            this.tau_pf = tau_pf;
            this.q_df = q_df;
            this.q_pf = q_pf;
        }

        public static JointScaled32Msg Deserialize(MessageDeserializer deserializer) => new JointScaled32Msg(deserializer);

        private JointScaled32Msg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.tau_s);
            deserializer.Read(out this.q);
            deserializer.Read(out this.tau_df);
            deserializer.Read(out this.tau_pf);
            deserializer.Read(out this.q_df);
            deserializer.Read(out this.q_pf);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.tau_s);
            serializer.Write(this.q);
            serializer.Write(this.tau_df);
            serializer.Write(this.tau_pf);
            serializer.Write(this.q_df);
            serializer.Write(this.q_pf);
        }

        public override string ToString()
        {
            return "JointScaled32Msg: " +
            "\ntau_s: " + tau_s.ToString() +
            "\nq: " + q.ToString() +
            "\ntau_df: " + tau_df.ToString() +
            "\ntau_pf: " + tau_pf.ToString() +
            "\nq_df: " + q_df.ToString() +
            "\nq_pf: " + q_pf.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
